### ISSUE TITLE
硬件 SPI 图像变形

### ISSUE THREAD

**Issue by wuhanstudio** [wuhanstudio/rt-u8g2#1]
> 如果使用硬件SPI不知道为什么，图像会出现一些变形

正常的图像：

![IMG_20190504_201739](https://user-images.githubusercontent.com/15157070/57178876-79935700-6ea1-11e9-9d7d-098006cafe5f.jpg)

变形的图像 ：

![IMG_20190504_201449](https://user-images.githubusercontent.com/15157070/57178875-79935700-6ea1-11e9-9d40-fefeb26d4e3a.jpg)

> 软件 I2C / 硬件I2C，软件 SPI 都是正常的

**Comment by seventh-yuan** [comment]
我遇到了类似的问题，初步判断是因为CS先没有按照芯片是时序设置, package中，好像是每次发一个字节的数据，这样每次都会更改CS

**Comment by seventh-yuan** [comment]
使用这个类U8G2_SSD1306_128X64_NONAME_F_4W_HW_SPI，没有出现图像变形的问题

**Comment by wuhanstudio** [comment]
感谢，原来是例程里我写错初始化函数了
