### ISSUE TITLE
使用中文显示不全

### ISSUE THREAD

**Issue by PeakRacing** [wuhanstudio/rt-u8g2#11]
使用中文显示历程 “你好世界”正常显示，测试其他无法全部显示，比如“音乐测试”使用u8g2_font_unifont_t_chinese2只能显示“音”，使用u8g2_font_unifont_t_chinese3显示“音乐”，测试显示不出来，请问是因为字库不全的原因么？

**Comment by wuhanstudio** [comment]
是的，这里有更全的字库 https://github.com/larryli/u8g2_wqy

**Comment by PeakRacing** [comment]
谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "吴晗"<notifications@github.com&gt;; 
发送时间: 2020年5月19日(星期二) 下午5:10
收件人: "wuhanstudio/rt-u8g2"<rt-u8g2@noreply.github.com&gt;; 
抄送: "Silly roe deer"<1473454180@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wuhanstudio/rt-u8g2] 使用中文显示不全 (#11)





 
是的，这里有更全的字库 https://github.com/larryli/u8g2_wqy
