### ISSUE TITLE
关于菜单历程按键问题

### ISSUE THREAD

**Issue by PeakRacing** [wuhanstudio/rt-u8g2#12]
您好，我尝试使用按键历程，修改为硬件SPI 方式驱动，屏幕正常显示，可是按键无响应，按键引脚已经自定义，请问可能是什么原因呢？？？

**Comment by wuhanstudio** [comment]
可以看看论坛这里，多半是按键响应比较慢

https://www.rt-thread.org/qa/forum.php?mod=viewthread&tid=12285&highlight=u8g2%2B%E6%8C%89%E9%94%AE

**Comment by PeakRacing** [comment]
您好，我之前看了这个帖子，所以使用了硬件SPI，我按按键一分钟还是没反应，可能不是响应慢

**Comment by wuhanstudio** [comment]
那可能性就太多了，电路、接线、代码 ...
建议在论坛上提供 MCU 型号，RTT 版本，原理图，部分代码问问看看，毕竟嵌入式如果不知道具体的硬件条件、代码，别人很难帮忙找到问题的

**Comment by PeakRacing** [comment]
您好，我将代码和图片发出来了，如果您有时间希望可以看一下，非常感谢  https://www.rt-thread.org/qa/thread-424868-1-1.html
