### ISSUE TITLE
关于使用u8g2之后无法擦除flash问题

### ISSUE THREAD

**Issue by PeakRacing** [wuhanstudio/rt-u8g2#13]
您好，我使用了硬件SPI的u8g2，功能正常，后来调试OTA时发现片内flash擦写失败，提示：[E/FAL] (fal_partition_erase:510) Partition erase error! Flash device(onchip_flash) erase error!
去掉u8g2线程初始化就正常擦写，后来新建工程只添加硬件SPI 和FAL，还是同样的状况，使用的是ST官方的L496ZG开发板，rtt4.0.2，最新软件包
论坛提问在这https://club.rt-thread.org/ask/question/424969.html
希望您有时间的话帮忙看一下，可能是哪里的问题，十分感谢

**Comment by wuhanstudio** [comment]
可能 SPI 初始化确实有些问题：
https://github.com/wuhanstudio/rt-u8g2/issues/1

SPI 初始化的代码在这里，你可以看看：
https://github.com/wuhanstudio/rt-u8g2/blob/c86fb5aa7c37d87f600e89ca00dcd76a69908ca2/port/u8g2_port.cpp#L36-L64

最近实验室事情比较多，不好意思可能没有时间调试，之后有时间我会再看看硬件 SPI 的初始化问题

**Comment by PeakRacing** [comment]
好的，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "吴晗"<notifications@github.com&gt;; 
发送时间: 2020年7月8日(星期三) 上午10:07
收件人: "wuhanstudio/rt-u8g2"<rt-u8g2@noreply.github.com&gt;; 
抄送: "Silly roe deer"<1473454180@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wuhanstudio/rt-u8g2] 关于使用u8g2之后无法擦除flash问题 (#13)





 
可能 SPI 初始化确实有些问题：
 #1
 
SPI 初始化的代码在这里，你可以看看：
 https://github.com/wuhanstudio/rt-u8g2/blob/c86fb5aa7c37d87f600e89ca00dcd76a69908ca2/port/u8g2_port.cpp#L36-L64
 
最近实验室事情比较多，不好意思可能没有时间调试，之后有时间我会再看看硬件 SPI 的初始化问题
