### ISSUE TITLE
bus fault: SCB_CFSR_BFSR:0x04 IMPRECISERR

### ISSUE THREAD

**Issue by mumu3w** [wuhanstudio/rt-u8g2#14]
![捕获11](https://user-images.githubusercontent.com/15176844/92991604-ad5fa180-f517-11ea-99ca-1f17415a35d2.PNG)

板子:stm32f103c8,stm32f103ze测试都是同样的问题.
使用的是 硬件spi1  pa5 pa7; 
pa0 pa1 pa2(似乎和后3个引脚有关)

**Comment by mumu3w** [comment]
问题找到了
u8g2_port.cpp文件

struct rt_hw_spi_cs
{
    rt_uint32_t pin;
};
----------->
struct rt_hw_spi_cs
{
    GPIO_TypeDef* GPIOx;
    rt_uint16_t pin;
};

drv_spi.c中
static rt_uint32_t spixfer(struct rt_spi_device *device, struct rt_spi_message *message)
{
...
struct stm32_hw_spi_cs *cs = device->parent.user_data;
...
}

在drv_spi.h中
struct stm32_hw_spi_cs
{
    GPIO_TypeDef* GPIOx;
    uint16_t GPIO_Pin;
};

**Comment by mumu3w** [comment]
或者在文件drv_spi.c中的static rt_uint32_t spixfer(struct rt_spi_device *device, struct rt_spi_message *message)函数

HAL_GPIO_WritePin(cs->GPIOx, cs->GPIO_Pin, GPIO_PIN_RESET); 
------->
rt_pin_write(*(rt_uint32_t *)device->parent.user_data, GPIO_PIN_RESET);

HAL_GPIO_WritePin(cs->GPIOx, cs->GPIO_Pin, GPIO_PIN_SET); 
------->
rt_pin_write(*(rt_uint32_t *)device->parent.user_data, GPIO_PIN_SET);

其余保持不变.

**Comment by wuhanstudio** [comment]
> 或者在文件drv_spi.c中的static rt_uint32_t spixfer(struct rt_spi_device *device, struct rt_spi_message *message)函数
> 
> HAL_GPIO_WritePin(cs->GPIOx, cs->GPIO_Pin, GPIO_PIN_RESET);
> ------->
> rt_pin_write(*(rt_uint32_t *)device->parent.user_data, GPIO_PIN_RESET);
> 
> HAL_GPIO_WritePin(cs->GPIOx, cs->GPIO_Pin, GPIO_PIN_SET);
> ------->
> rt_pin_write(*(rt_uint32_t *)device->parent.user_data, GPIO_PIN_SET);
> 
> 其余保持不变.

谢谢你分享解决问题的方法，不过这样子就调用了 STM32 的库函数了，其他的板子就用不了，还是希望RTT软件包和具体硬件能解耦。

硬件 SPI 确实有点问题，之前没找到时间修改，有一个 PR 修改了 SPI 发送函数，速度更快，我之后试试

**Comment by mumu3w** [comment]
> > 或者在文件drv_spi.c中的static rt_uint32_t spixfer(struct rt_spi_device *device, struct rt_spi_message *message)函数
> > HAL_GPIO_WritePin(cs->GPIOx, cs->GPIO_Pin, GPIO_PIN_RESET);
> > ------->
> > rt_pin_write(*(rt_uint32_t *)device->parent.user_data, GPIO_PIN_RESET);
> > HAL_GPIO_WritePin(cs->GPIOx, cs->GPIO_Pin, GPIO_PIN_SET);
> > ------->
> > rt_pin_write(*(rt_uint32_t *)device->parent.user_data, GPIO_PIN_SET);
> > 其余保持不变.
> 
> 谢谢你分享解决问题的方法，不过这样子就调用了 STM32 的库函数了，其他的板子就用不了，还是希望RTT软件包和具体硬件能解耦。
> 
> 硬件 SPI 确实有点问题，之前没找到时间修改，有一个 PR 修改了 SPI 发送函数，速度更快，我之后试试

个人感觉rtt的pin应该由bsp/xxx/libraries/目录下的drv_xxx.c把rtt的pin转成对应bsp的pin.

**Comment by wuhanstudio** [comment]
感谢 ArnoYuan，这个问题已经修复了：

https://github.com/wuhanstudio/rt-u8g2/pull/10
