### ISSUE TITLE
请教使用u8g2使用软件三线制spi怎么修改初始化参数的问题

### ISSUE THREAD

**Issue by douzhipeng** [wuhanstudio/rt-u8g2#15]
使用了一个屏幕，三线制spi接口，案例中没有找到对应的测试例程，想修改一下u8g2初始化方法，不知怎么改，因此想请教一下，望您在百忙之中帮我解答，谢谢

**Comment by jzz007** [comment]
首先你得知道你得屏幕u8g2是否支持。你先查你的屏幕的控制芯片的型号，然后到readme文档中给的网址找找有没有你这个型号。

**Comment by douzhipeng** [comment]
> 首先你得知道你要屏幕u8g2是否支持。你先查你的屏幕的控制芯片的型号，然后到readme文档中给的网址找找没有你这个型号。

驱动芯片是ST7920呢   应该是支持的

**Comment by wuhanstudio** [comment]
你好，st7920 的三线 SPI 液晶屏似乎比较少见吧，是不是这样的

https://www.pianshen.com/article/4800659574/

如果是这个，本身 u8g2 就是支持三线的：

https://www.onetransistor.eu/2018/03/code-text-mode-st7920-arduino.html
