### ISSUE TITLE
在rt-thread中使用，keil5编译的时候出现的小问题

### ISSUE THREAD

**Issue by shao7936626** [wuhanstudio/rt-u8g2#2]
port下面的是cpp文件，keil5默认不支持呢，如何修改才能编译通过啊

**Comment by wuhanstudio** [comment]
你好，如果 Keil 识别为 C 文件，在文件上右键 Options for u8g2_port.cpp 可以修改为 CPP

![TIM截图20190506173930](https://user-images.githubusercontent.com/15157070/57217958-3f9b8f80-701e-11e9-8a39-fb00d92c5a63.png)

不过如果是用 menuconfig 选择 u8g2，然后 scons --target=mdk5 -s 的话，默认U8g2的源文件Keil是按CPP添加进去的。

![TIM截图20190506173831](https://user-images.githubusercontent.com/15157070/57217892-167aff00-701e-11e9-8cdd-56bd616d3a5e.png)

顺便一提，如果自己的源代码引用了 u8g2 头文件，比如 main,c 需要改为 main.cpp 才能被 Keil 正常识别编译。

**Comment by shao7936626** [comment]
按照你的提示，已经顺利通过编译了，真是十分感谢；
然后还有一些小问题：

1. 如果要使用rt-u8g2这个库，好像必须在stcubemx中打开一个spi，不然的话，编译的时候会缺少spi定义的宏（忘记截图了）

2. 按照你的提示，顺利编译和烧写后，还是没有字符输出，不清楚是什么原因。
我简单说一下我目前的情况：
          **mcu: STM32F103RCT6**
          **lcd:   st7567**
![TIM图片20190507220142](https://user-images.githubusercontent.com/7930291/57305467-b9617500-7113-11e9-9324-7501168f8912.png)

        原理图：
![TIM图片20190507220237](https://user-images.githubusercontent.com/7930291/57305583-e6158c80-7113-11e9-9e69-a628d8398a83.png)
![TIM图片20190507220259](https://user-images.githubusercontent.com/7930291/57305585-e746b980-7113-11e9-90a7-595abb9c6e1f.png)

然后cubemx中没有把spi3打开
![TIM图片20190507220448](https://user-images.githubusercontent.com/7930291/57305773-270da100-7114-11e9-8bdb-33d2b4ac1220.png)
menuconfig中硬件上的spi口和u8g2中的spi都没有开：
![image](https://user-images.githubusercontent.com/7930291/57305878-52908b80-7114-11e9-805e-36e92d14cafd.png)
![image](https://user-images.githubusercontent.com/7930291/57305904-61773e00-7114-11e9-8b9e-cb9a493d3642.png)
源码中：
![image](https://user-images.githubusercontent.com/7930291/57306049-af8c4180-7114-11e9-84ab-77ad5c0c5564.png)
GPIO定义：
![BWVP~ONH{_2F%FHHNTLA`{N](https://user-images.githubusercontent.com/7930291/57307550-596ccd80-7117-11e9-9f2e-2b7f149974f5.png)



源码搬的例子里面的，改成了st7567
![TIM图片20190507222816](https://user-images.githubusercontent.com/7930291/57307608-743f4200-7117-11e9-9ee1-cc2c77c996d7.png)



![image](https://user-images.githubusercontent.com/7930291/57306095-ca5eb600-7114-11e9-8220-ce0459aa4307.png)这行代码换过u8g2lib.h中的1,2,f 都没有效果
![image](https://user-images.githubusercontent.com/7930291/57306227-0c87f780-7115-11e9-864c-003b2645e71b.png)

代码显示运行过，但是经过-o3 处理，不知道会不会出问题
![image](https://user-images.githubusercontent.com/7930291/57306280-2295b800-7115-11e9-9d1d-617a73124b6e.png)

**Comment by wuhanstudio** [comment]
看你现在用的是 STM32F103RCT6，搭配屏幕是软件SPI (4W_SW_SPI)，我有几个建议一步步排查错误：

1. 使用 [rt-thread 官方的 bsp]( https://github.com/rt-thread/rt-thread
)，下载下来在 rt-thread/bsp/stm32f10x-HAL 文件夹下右键 ConEmu Here 就可以了，会方便很多。因为你现在用的是 CubeMX，如果用官方的 bsp 运行正常，这样可能就是 CubeMX 配置错误，因为用软件SPI其实是不需要打开硬件 spi 的；

2. 我看图上的 GPIO定义和我的不一样，在 rt-thread\bsp\stm32f10x-HAL\drivers\drv_gpio.c 下有定义，一般 GPIO 标号是按照芯片原理图里面的实际标号定义的，比如 PB5--> 57, PB6-->58

![TIM截图20190507144425](https://user-images.githubusercontent.com/15157070/57308792-84582100-7119-11e9-86eb-abdcb2fca50b.png)

如果使用官方的 bsp，引脚标号修改后还是有问题，我最近也可以买一块 st7567 测试一下，因为我不像 olikraus 那样有那么多屏幕一个一个测试 ;)

**Comment by shao7936626** [comment]
感谢回复的那么快，关于pin的问题，我也很奇怪，目前的bsp是我自制的，因为板子上面直连了led等和button，我目前都已经弄通，发现gpio口是没有问题，我刚刚又尝试了一下rtt4.0 bsp下的stm32f10x-hal，
直接menuconfig添加u8g2就出现我开始说的问题，他调用到了drv_spi.h，我其他什么都没做
![TIM图片20190507231447](https://user-images.githubusercontent.com/7930291/57311421-35f95100-711e-11e9-8838-103e9e8f788f.png)

**Comment by wuhanstudio** [comment]
这是官方 bsp 的一个小问题，只要在 drv_spi.h 包含一个头文件就可以了，添加的头文件可以直接查看定义就找到了。

![TIM图片20190507152504](https://user-images.githubusercontent.com/15157070/57311946-32b29500-711f-11e9-90fe-4a2d2bb35279.png)

当然，要勾选 Browse Information 编译后才能转到定义

![TIM图片20190507152617](https://user-images.githubusercontent.com/15157070/57312037-5d045280-711f-11e9-843f-8f798eb9fab6.png)

我一直在考虑要不要提个 issue，可能也是不同板子需要包含的头文件不同，所以没有加上。

**Comment by wuhanstudio** [comment]
顺便一提，用官方的 bsp 也可以在 STM32F10x-HAL 目录下使用 scons --dist 来生成完全独立的项目文件，可以随意拷贝到任何目录下运行，我感觉用官方的 bsp 测试还是比较方便的。

**Comment by shao7936626** [comment]
根据rtt4.0的stm32f103-hal 后在drv_spi.h里面添加头文件顺利编译后，还是不能够在屏幕上显示，我用类似于串口模拟的可以输出字符的，但是可玩性太低了

**Comment by wuhanstudio** [comment]
我之前都是用 ssd1306 的 SPI 和 I2C 测试的，我这几天也买一块 st7567 试试吧，稍等

**Comment by shao7936626** [comment]
我邮件发给你了，我这边有块板子，你给个地址我，我直接发给你

**Comment by jzz007** [comment]
调试这类应用的时候有个逻辑分析仪也许大概应该就不会这么抓瞎吧

**Comment by shao7936626** [comment]
> 调试这类应用的时候有个逻辑分析仪也许大概应该就不会这么抓瞎吧

也是，现在垃圾的24M分析仪，30块钱一个，我去买一个玩一玩

**Comment by wuhanstudio** [comment]
我试了一下，其实是正常显示了，只是对比度原因很难看清，哈哈

![IMG_20190510_164253](https://user-images.githubusercontent.com/15157070/57514327-6ddce000-733a-11e9-986b-128e314cc08e.jpg)

**Comment by shao7936626** [comment]
> 我试了一下，其实是正常显示了，只是对比度原因很难看清，哈哈
> 
> ![IMG_20190510_164253](https://user-images.githubusercontent.com/15157070/57514327-6ddce000-733a-11e9-986b-128e314cc08e.jpg)

先说一下你成功的步骤吧，是用的软件模拟额还是用的硬件spi啊，还有分辨率，可能他没调整分辨率的命令下去

**Comment by wuhanstudio** [comment]
我用的四线软件 SPI

    #define OLED_SPI_PIN_CLK                  55  // PB3
    #define OLED_SPI_PIN_MOSI                 56  // PB4
    #define OLED_SPI_PIN_RES                  58  // PB6
    #define OLED_SPI_PIN_DC                   57  // PB5
    #define OLED_SPI_PIN_CS                   59  // PB7
    #define OLED_SPI_LIGHT                    61  // PB8
    
    // Check https://github.com/olikraus/u8g2/wiki/u8g2setupcpp for all supported devices
    static U8X8_ST7567_JLX12864_4W_SW_SPI u8x8(U8G2_R0, 
                                            /* clock=*/ OLED_SPI_PIN_CLK, 
                                            /* data=*/ OLED_SPI_PIN_MOSI, 
                                            /* cs=*/ OLED_SPI_PIN_CS, 
                                            /* dc=*/ OLED_SPI_PIN_DC, 
                                            /* reset=*/ OLED_SPI_PIN_RES);

**Comment by shao7936626** [comment]
你看看把软件打个包给我，我再来试试看

**Comment by wuhanstudio** [comment]
你先试试用这个 main.cpp 吧，我等下把完整项目打个包
    
    #include <rtthread.h>
    #include <U8g2lib.h>

    // Check https://github.com/olikraus/u8g2/wiki/u8g2setupcpp for all supported devices
    #define OLED_SPI_PIN_CLK                   55  // PB3
    #define OLED_SPI_PIN_MOSI                  56  // PB4
    #define OLED_SPI_PIN_RES                   58  // PB6
    #define OLED_SPI_PIN_DC                    57  // PB5
    #define OLED_SPI_PIN_CS                    59  // PB7
    #define OLED_SPI_LIGHT			   61  // PB8
    // Check https://github.com/olikraus/u8g2/wiki/u8g2setupcpp for all supported devices
    static U8G2_ST7567_JLX12864_F_4W_SW_SPI u8g2(U8G2_R0, 
                                                /* clock=*/ OLED_SPI_PIN_CLK, 
                                                /* data=*/ OLED_SPI_PIN_MOSI, 
                                                /* cs=*/ OLED_SPI_PIN_CS, 
                                                /* dc=*/ OLED_SPI_PIN_DC, 
                                                /* reset=*/ OLED_SPI_PIN_RES);

    int main(void)
    {
        rt_pin_mode(OLED_SPI_LIGHT, PIN_MODE_OUTPUT);
        rt_pin_write(OLED_SPI_LIGHT, PIN_HIGH);
        /* user app entry */
        u8g2.begin();
        u8g2.clearBuffer();                         // clear the internal memory
        u8g2.setFont(u8g2_font_6x13_tr);            // choose a suitable font
        u8g2.drawStr(1, 18, "U8g2 on RT-Thread");   // write something to the internal memory
        u8g2.sendBuffer();                          // transfer internal memory to the display
        u8g2.setFont(u8g2_font_unifont_t_symbols);
        u8g2.drawGlyph(112, 56, 0x2603 );
        u8g2.sendBuffer();
        return 0;
    }

**Comment by wuhanstudio** [comment]
这是完整的 bsp 文件

[https://wuhanstudio-1252843818.cos.ap-shanghai.myqcloud.com/stm32f10x-HAL.zip](https://wuhanstudio-1252843818.cos.ap-shanghai.myqcloud.com/stm32f10x-HAL.zip)

**Comment by wuhanstudio** [comment]
如果需要调节对比度的话，这样就可以了，看起来挺清楚的

    u8g2.begin();
    u8g2.setContrast(128);

![1557480758116](https://user-images.githubusercontent.com/15157070/57517547-4ccbbd80-7341-11e9-9e05-8143034f40bb.jpg)

**Comment by shao7936626** [comment]
> 如果需要调节对比度的话，这样就可以了，看起来挺清楚的
> 
> ```
> u8g2.begin();
> u8g2.setContrast(128);
> ```
> 
> ![1557480758116](https://user-images.githubusercontent.com/15157070/57517547-4ccbbd80-7341-11e9-9e05-8143034f40bb.jpg)

十分感谢，为何我看你的GPIO数值和drv_gpio里面的不一样，而且这个我也一直搞懂，我开始发给你的那份能点亮的，IO数值更不一样了

**Comment by wuhanstudio** [comment]
这里面引脚定义和实际不匹配，不过因为后面注释掉了所以没有影响:

![TIM截图20190510204438](https://user-images.githubusercontent.com/15157070/57528532-c7560680-735c-11e9-88bc-4327e802566c.png)

**Comment by shao7936626** [comment]
> 这里面引脚定义和实际不匹配，不过因为后面注释掉了所以没有影响:
> 
> ![TIM截图20190510204438](https://user-images.githubusercontent.com/15157070/57528532-c7560680-735c-11e9-88bc-4327e802566c.png)

这个是比较奇怪，我自制的BSP的引脚数值和他项目直接有的居然不一样，我开始还纳闷呢，目前我这边也弄好了，我来看看如何添加中文显示

**Comment by shao7936626** [comment]
复制了[这个例子](https://github.com/wuhanstudio/rt-u8g2/blob/master/examples/full_buffer/IconMenu.cpp)， 到你提供的BSP里面 ，
然后定义了GPIO
![image](https://user-images.githubusercontent.com/7930291/57571741-59850a00-7444-11e9-8d8f-972d8e0af2d9.png)
![image](https://user-images.githubusercontent.com/7930291/57571755-76b9d880-7444-11e9-8366-73ddcf6344f8.png)
然后把pin mode 设置输入
![image](https://user-images.githubusercontent.com/7930291/57571768-a23cc300-7444-11e9-988f-223ed07a582a.png)
按了按钮，界面不动
然后我把multi_button 加进来测试了一下，显示按钮触发了
![image](https://user-images.githubusercontent.com/7930291/57571904-66a2f880-7446-11e9-8d7a-d93206905933.png)
然后把，对应u8g2里面to_right和ot_left到mutli_button 下，能移动，速度（超级慢）

**Comment by wuhanstudio** [comment]
我刚试了一下这样是可以的，如果用的是软件 SPI 会因为刷屏速度比较慢，导致按键检测不是那么实时
只要按键按下 1-2s 再松开就可以了

    #define U8G2_PIN_UP                         8      // LED1 Not Used
    #define U8G2_PIN_DOWN                       9      // LED2 Not Used
    #define U8G2_PIN_LEFT                       39     // KEY3 PC8
    #define U8G2_PIN_RIGHT                      37     // KEY4 PC6
    #define U8G2_PIN_SELECT                     14     // KEY1 PA0
    #define U8G2_PIN_HOME                       40     // KEY2 PC9

![录制_2019_05_12_16_50_46_620_20190512165155](https://user-images.githubusercontent.com/15157070/57580000-9bf32900-74ce-11e9-8805-6b4a3da959d5.gif)

**Comment by shao7936626** [comment]
> 我刚试了一下这样是可以的，如果用的是软件 SPI 会因为刷屏速度比较慢，导致按键检测不是那么实时
> 只要按键按下 1-2s 再松开就可以了
> 
> ```
> #define U8G2_PIN_UP                         8      // LED1 Not Used
> #define U8G2_PIN_DOWN                       9      // LED2 Not Used
> #define U8G2_PIN_LEFT                       39     // KEY3 PC8
> #define U8G2_PIN_RIGHT                      37     // KEY4 PC6
> #define U8G2_PIN_SELECT                     14     // KEY1 PA0
> #define U8G2_PIN_HOME                       40     // KEY2 PC9
> ```
> 
> ![录制_2019_05_12_16_50_46_620_20190512165155](https://user-images.githubusercontent.com/15157070/57580000-9bf32900-74ce-11e9-8805-6b4a3da959d5.gif)

硬件SPI我尝试了一下，没有点亮起来，现在这个stm32f10x-hal里面的spi驱动，好像是老的，api和文档里面的也不一样

**Comment by wuhanstudio** [comment]
硬件 SPI 恐怕就要改电路了，这些是 F103RC 的硬件 SPI

    #define OLED_SPI_PIN_CLK                   21  // PA5
    #define OLED_SPI_PIN_MOSI                  23  // PA7
    #define OLED_SPI_PIN_RES                   16  // PA2
    #define OLED_SPI_PIN_DC                    15  // PA1
    #define OLED_SPI_PIN_CS                    14  // PA0

**Comment by shao7936626** [comment]
> 硬件 SPI 恐怕就要改电路了，这些是 F103RC 的硬件 SPI
> 
> ```
> #define OLED_SPI_PIN_CLK                   21  // PA5
> #define OLED_SPI_PIN_MOSI                  23  // PA7
> #define OLED_SPI_PIN_RES                   16  // PA2
> #define OLED_SPI_PIN_DC                    15  // PA1
> #define OLED_SPI_PIN_CS                    14  // PA0
> ```

难怪我开始错的，开始的时候把硬件spi1打开了，然后端口对那边去了
