### ISSUE TITLE
[添加硬件 SPI 编译错误] SPI_TypeDef is undefined

### ISSUE THREAD

**Issue by wuhanstudio** [wuhanstudio/rt-u8g2#4]
很多常见的问题我就都在这里总结一下了

**Comment by wuhanstudio** [comment]
这是官方 bsp 的一个小问题，只要在 drv_spi.h 包含一个头文件就可以了，添加的头文件可以直接查看定义就找到了。

![TIM图片20190507152504](https://user-images.githubusercontent.com/15157070/57311946-32b29500-711f-11e9-90fe-4a2d2bb35279.png)

当然，要勾选 Browse Information 编译后才能转到定义

![TIM图片20190507152617](https://user-images.githubusercontent.com/15157070/57312037-5d045280-711f-11e9-843f-8f798eb9fab6.png)

_Originally posted by @wuhanstudio in https://github.com/wuhanstudio/rt-u8g2/issues/2#issuecomment-490127622_

**Comment by wuhanstudio** [comment]
实际上最新版本 stm32f10x-HAL 的 bsp 已经被移除了，这是 rt-thread 建议：

stm32f10x-HAL 该 BSP 已经逐渐不再维护了，推荐使用 stm32 目录下的 BSP。

https://github.com/RT-Thread/rt-thread/tree/master/bsp/stm32

_Originally posted by @SummerGGift in https://github.com/RT-Thread/rt-thread/issues/2709#issuecomment-494659927_

**Comment by shao7936626** [comment]
用stm32下的bsp，注意GPIO定义的规则不一样，前期会百般不适应的
