### ISSUE TITLE
关于调用u8G2库的问题

### ISSUE THREAD

**Issue by bjjdyx345** [wuhanstudio/rt-u8g2#5]
你好，我用你的库已经在F429上跑通了demo。但是我还是有几个问题不明白要问一下。我看了下这个源代码用了还是c的源码，然后你封装成了Cpp。我也看了你给其他人回复的，给的例程也都是cpp。因为大部分咱们用到的都是C比较多，用C的话，是不是直接调用里边的C函数就行了？如果调用C++的话，应该怎么写比较合适？

**Comment by wuhanstudio** [comment]
你好，

1.x.x 版本是用的 C，可以参考这个：

[https://github.com/wuhanstudio/rt-u8g2/blob/v1.2.0/examples/ssd1306_12864_sw_i2c_example.c](https://github.com/wuhanstudio/rt-u8g2/blob/v1.2.0/examples/ssd1306_12864_sw_i2c_example.c)

这是 C 版本的初始化 API：
[https://github.com/olikraus/u8g2/wiki/u8g2setupc](https://github.com/olikraus/u8g2/wiki/u8g2setupc)

2.x.x 版本封装了 C++，这是 C++ 的 API，里面也有对应的 C 的 API：

https://github.com/olikraus/u8g2/wiki/u8g2reference

这是 C++ 版本的初始化 API：

[https://github.com/olikraus/u8g2/wiki/u8g2setupcpp](https://github.com/olikraus/u8g2/wiki/u8g2setupcpp)

**Comment by bjjdyx345** [comment]
> 你好，
> 
> 1.x.x 版本是用的 C，可以参考这个：
> 
> https://github.com/wuhanstudio/rt-u8g2/blob/v1.2.0/examples/ssd1306_12864_sw_i2c_example.c
> 
> 这是 C 版本的初始化 API：
> https://github.com/olikraus/u8g2/wiki/u8g2setupc
> 
> 2.x.x 版本封装了 C++，这是 C++ 的 API，里面也有对应的 C 的 API：
> 
> https://github.com/olikraus/u8g2/wiki/u8g2reference
> 
> 这是 C++ 版本的初始化 API：
> 
> https://github.com/olikraus/u8g2/wiki/u8g2setupcpp

感谢，已经切换到1.X了。
